
import Layout from '@/components/layout/Layout';
import { Link } from 'react-router-dom';

const TermsOfServicePage = () => {
  return (
    <Layout>
      <div className="bg-gradient-to-b from-infernal-950 to-infernal-900 text-white py-12">
        <div className="container mx-auto px-4">
          <h1 className="text-3xl md:text-4xl font-gothic mb-4 text-center">Terms of Service</h1>
          <p className="text-lg max-w-3xl mx-auto text-center opacity-90">
            Last Updated: April 16, 2023
          </p>
        </div>
      </div>

      <section className="py-12 bg-white">
        <div className="container mx-auto px-4 max-w-4xl">
          <div className="prose prose-lg prose-infernal mx-auto">
            <p>
              Welcome to DnD Tiefling Name Generator! These Terms of Service ("Terms") govern your use of our website 
              located at https://dndtieflingnamegenerator.com/ ("Website") and all related services. Please read these Terms 
              carefully.
            </p>
            <p>
              By accessing or using our Website, you agree to be bound by these Terms. If you disagree with any part of the Terms, 
              then you may not access the Website.
            </p>

            <h2>Use of the Service</h2>
            <p>
              The DnD Tiefling Name Generator is designed to help users create names for fictional characters used in 
              tabletop role-playing games, particularly Dungeons & Dragons. You agree to use the service only for its 
              intended purpose and in compliance with all applicable laws and regulations.
            </p>
            
            <h2>Intellectual Property</h2>
            <p>
              The Website and its original content, features, and functionality are owned by DnD Tiefling Name Generator 
              and are protected by international copyright, trademark, patent, trade secret, and other intellectual property 
              laws.
            </p>
            <p>
              Generated names are provided for personal use in fictional role-playing game contexts. You may use the names 
              generated by our tool for your personal characters, campaigns, and creative works. However, mass collection 
              or automated harvesting of generated names for commercial purposes is prohibited without prior written consent.
            </p>
            <p>
              "Dungeons & Dragons" and "D&D" are trademarks of Wizards of the Coast LLC. This website is not affiliated with, 
              endorsed, sponsored, or specifically approved by Wizards of the Coast LLC. We acknowledge the proprietary rights 
              of Wizards of the Coast in its trademarks and other intellectual property.
            </p>
            
            <h2>User-Generated Content</h2>
            <p>
              If you submit feedback, suggestions, or other information to us regarding our Website, you grant us a 
              non-exclusive, worldwide, royalty-free, perpetual, and irrevocable right to use, reproduce, modify, adapt, 
              publish, translate, create derivative works from, distribute, and display such content.
            </p>
            
            <h2>Limitation of Liability</h2>
            <p>
              In no event shall DnD Tiefling Name Generator, nor its directors, employees, partners, agents, suppliers, or 
              affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without 
              limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
            </p>
            <ol>
              <li>Your access to or use of or inability to access or use the Website;</li>
              <li>Any conduct or content of any third party on the Website;</li>
              <li>Any content obtained from the Website; and</li>
              <li>Unauthorized access, use or alteration of your transmissions or content.</li>
            </ol>
            
            <h2>Disclaimer</h2>
            <p>
              Our Website and its contents are provided on an "as is" and "as available" basis without any warranties of any 
              kind. We do not warrant that the Website will be uninterrupted, timely, secure, or error-free.
            </p>
            <p>
              We make no representations or warranties regarding the accuracy or completeness of the names generated, 
              their suitability for any particular purpose, or that they will meet your specific requirements.
            </p>
            
            <h2>Third-Party Links</h2>
            <p>
              Our Website may contain links to third-party websites or services that are not owned or controlled by 
              DnD Tiefling Name Generator. We have no control over, and assume no responsibility for, the content, 
              privacy policies, or practices of any third-party websites or services.
            </p>
            
            <h2>Termination</h2>
            <p>
              We may terminate or suspend your access to the Website immediately, without prior notice or liability, 
              for any reason whatsoever, including, without limitation, if you breach the Terms.
            </p>
            
            <h2>Changes</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is 
              material, we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes 
              a material change will be determined at our sole discretion.
            </p>
            <p>
              By continuing to access or use our Website after those revisions become effective, you agree to be bound by the 
              revised terms.
            </p>
            
            <h2>Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of the United States, without regard 
              to its conflict of law provisions.
            </p>
            
            <h2>Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us through our <Link to="/contact" className="text-infernal-700 hover:text-infernal-900">Contact Page</Link>.
            </p>
          </div>
        </div>
      </section>
    </Layout>
  );
};

export default TermsOfServicePage;
